name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
      - 'documentation'
  - title: '⚡ Performance'
    labels:
      - 'performance'
      - 'optimization'
  - title: '🔄 Dependencies'
    labels:
      - 'dependencies'
      - 'deps'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'bugfix'
      - 'fix'
      - 'maintenance'
      - 'docs'
      - 'dependencies'
  default: patch

template: |
  ## Changes

  $CHANGES
  
  ## Docker
  ```
  docker pull lakker/pulsarr:$RESOLVED_VERSION
  ```

  ## Contributors
  
  $CONTRIBUTORS