name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'src/**'  # OpenAPI generation depends on source files
      - 'scripts/**'  # Build scripts
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/deploy-docs-production.yml'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for proper git history

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install root dependencies
        run: npm ci

      - name: Install docs dependencies
        run: |
          cd docs
          npm ci

      - name: Generate OpenAPI spec and build documentation
        run: npm run docs:build

      - name: Deploy to GitHub Pages
        run: |
          cd docs
          npm run deploy
        env:
          GIT_USER: ${{ github.actor }}
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
          USE_SSH: false