name: Update Contributors

on:
  pull_request_target:
    types: [closed]
    branches: [master, develop]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-contributors:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.3.6
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        with:
          image_size: 42
          columns_per_row: 6
          readme_path: README.md
          use_username: true
          commit_message: "docs: update contributors [skip ci]"